providers:
  OpenAI:
    models:
      - gpt-3.5-turbo
      - gpt-4-turbo
      - gpt-4o-mini
      - gpt-4o
      - o1-mini
      - o1-preview
  Cohere:
    models:
      - command
      - xlarge
  HuggingFace:
    models:
      - gpt2
      - distilgpt2
